
PHZ = phz_load(gf('data','ec','phzfiles','scl.phz'));

PHZ = phz_blsub(PHZ,'baseline');

% PHZ = phz_rej(PHZ,0.1);

phz_plot(PHZ,...
    'pretty', 1,...
    'title', 0,...
    'summary', {'group'},...
    'feature', 'rt',...
    'subset', PHZ.resp.q1_rt < 7,...
    'save', gf('ec','plots','rt - rt < 7'))