
PHZ = phz_load(gf('data','ec','phzfiles','scl.phz'));

PHZ = phz_blsub(PHZ,'baseline');

PHZ = phz_rej(PHZ,0.1);

phz_writetable(PHZ,...
    'summary',{'participant','group','trials'},...
    'feature',{'mean','max','maxi','slope','slopei','area'},...
    'region',[1 5],...
    'subset',PHZ.resp.q1_rt < 7,...
    'save','stats/scl data - rt < 7.csv')