function ec_makeplots(datatype)

if nargin < 1, datatype = 'scr'; end

% options
datafile = gf('data','ec','phzfiles',[datatype,'.phz']);
savefolder = gf('ec','plots');

fontsize = 22;
simpleytitle = true;
plotsmooth = true;

% load data
PHZ = phz_load(datafile);
% PHZ.meta.spec.group{3} = [0 176/255 80/255];

%{

% physio plots
% ------------
PHZ = phz_blsub(PHZ, 'baseline');
PHZ = phz_rej(PHZ, 0.05);

% time-series
phz_plot(PHZ,... 
    'feature', '', 'save', fullfile(savefolder, 'scl (rej 0.05)'),...
    'pretty', 1, 'title', 0, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle, 'plotsmooth', plotsmooth,...
    'summary', {'group'})

phz_plot(PHZ,... 
    'feature', '', 'save', fullfile(savefolder, 'scl by emo (rej 0.05)'),...
    'pretty', 1, 'title', 1, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle, 'plotsmooth', plotsmooth,...
    'summary', {'group','trials'})

% bar
phz_plot(PHZ,... 
    'feature', 'mean', 'save', fullfile(savefolder, 'scl mean (rej 0.05)'),...
    'pretty', 1, 'title', 0, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle,...
    'summary', {'group'},'region',[1 5])

phz_plot(PHZ,... 
    'feature', 'mean', 'save', fullfile(savefolder, 'scl mean by emo (rej 0.05)'),...
    'pretty', 1, 'title', 1, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle,...
    'summary', {'group','trials'},'region',[1 5],'yl',[0 0.005])

PHZ = phz_blsub(PHZ, 0);
PHZ = phz_rej(PHZ, 0);


%}


% behavioural plots
% -----------------
PHZ = phz_subset(PHZ,PHZ.resp.q1_rt < 7);

phz_plot(PHZ,... 
    'feature', 'acc', 'save', fullfile(savefolder, 'acc (rt < 7)'),...
    'pretty', 1, 'title', 0, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle,...
    'sigstar',{{{'normal','aided'}},0.031,0,fontsize},...
    'summary', {'group'})

phz_plot(PHZ,... 
    'feature', 'acc', 'save', fullfile(savefolder, 'acc by emo (rt < 7)'),...
    'pretty', 1, 'title', 1, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle,...
    'summary', {'group','trials'})

phz_plot(PHZ,...
    'feature', 'rt','save', fullfile(savefolder, 'rt (rt < 7)'),...
    'pretty', 1, 'title', 0, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle,...
    'sigstar',{{{'normal','aided'},{'normal','impaired'}},[0.04 0.032],0,fontsize},...
    'summary', {'group'})

phz_plot(PHZ,... 
    'feature', 'rt','save', fullfile(savefolder, 'rt by emo (rt < 7)'),...
    'pretty', 1, 'title', 1, 'close', 1, 'fontsize', fontsize,...
    'simpleytitle', simpleytitle,...
    'summary', {'group','trials'})
    




end
