function ec_plot(phz,type)

savefolder = '~/r/ec/plots/';
ext = '.eps';
addpath('~/bin/matlab/phzlab')

fontsize = 28;

if nargin < 1
    phz = []; end

if nargin < 2
    type = ''; end

if nargin > 0 && ~isstruct(phz)
    type = phz; end




if isempty(type)
    type = {'acc','rt','sclMean','accByEmo','rtByEmo','sclMeanByEmo','sclByEmo'};
    % type = {'sclMean','sclMeanByEmo','sclByEmo'};
    % do_close = true;
    do_close = false;
else
    type = cellstr(type);
    do_close = false;
end

% get data
if isempty(phz)

    phz = phz_load('~/local/data/ec/phzfiles/scl.phz');
    phz = phz_blsub(phz,[-1 0]);
    phz = phz_rej(phz,0.05);

end

acc = phz_rej(phz,0,0);
acc = phz_subset(acc, phz.resp.q1_rt < 7); % for acc/rt, only include rt < 7 seconds

for i = 1:length(type)
    switch lower(type{i})
        
        case 'acc'
            phz_plot(acc, 'feature','acc', ...
                'save',fullfile(savefolder,['acc',ext]), ...
                'summary',{'group'}, ...
                'sigstar',{{ ...
                {'impaired','aided'}, ...
                {'normal','impaired'}, ...
                {'normal','aided'}}, ...
                [nan 0.052 0.0023], 1, fontsize}, ...
                'yl',[0 100], ...
                'fontsize',fontsize, 'close',1,...
                'pretty',true, 'title',false, 'simpleytitle',true)
            
        case 'rt'
            phz_plot(acc, 'feature','rt', ...
                'save',fullfile(savefolder,['rt',ext]), ...
                'summary',{'group'}, ...
                'sigstar',{{ ...
                {'normal','impaired'}, ...
                {'impaired','aided'}, ...
                {'normal','aided'}}, ...
                [0.003 nan 0.001], 1, fontsize}, ...
                'fontsize',fontsize, 'close',1,...
                'pretty',true, 'title',false, 'simpleytitle',true)
            
        case 'sclmean'
            phz_plot(phz, 'feature','mean', ...
                'save',fullfile(savefolder,['sclMean',ext]), ...
                'region',[2 6], ...
                'summary',{'group'}, ...
                'sigstar',{{...
                {'normal','impaired'}, ...
                {'impaired','aided'}, ...
                {'normal','aided'}}, ...
                [0.035 0.001 0.051], 1, fontsize}, ...
                'fontsize',fontsize, 'close',1,...
                'pretty',true, 'title',false, 'simpleytitle',true)

        case 'accbyemo'
            phz_plot(acc, 'feature','acc', ...
                'save',fullfile(savefolder,['accByEmo',ext]), ...
                'summary',{'group','trials'}, ...
                'fontsize',fontsize+4, 'close',1,...
                'pretty',true)

        case 'rtbyemo'
            phz_plot(acc, 'feature','rt', ...
                'save',fullfile(savefolder,['rtByEmo',ext]), ...
                'summary',{'group','trials'}, ...
                'fontsize',fontsize+4, 'close',1,...
                'pretty',true, 'simpleytitle',true)

        case 'sclmeanbyemo'
            phz_plot(phz, 'feature','mean', ...
                'save',fullfile(savefolder,['sclMeanByEmo',ext]), ...
                'region',[1 5], ...
                'summary',{'group','trials'}, ...
                'fontsize',fontsize+4, 'close',1,...
                'pretty',true, 'simpleytitle',true)

        case 'sclbyemo'
            phz_plot(phz, 'feature','', ...
                'save',fullfile(savefolder,['sclByEmo',ext]), ...
                'summary',{'group','trials'}, ...
                'fontsize',fontsize+4, 'close',1,...
                'pretty',true, 'smooth',true, 'simpleytitle',true)

        case 'sclbygroup'
            phz_plot(phz, 'feature','', ...
                'save',fullfile(savefolder,['sclByGroup',ext]), ...
                'summary',{'trials','group'}, ...
                'fontsize',fontsize+4, 'close',1,...
                'pretty',true, 'smooth',true, 'simpleytitle',true)
            
    end
    if do_close, close all, end
end         
