function ec_writetables

suffix = '_with_stimulus_name';

PHZ = phz_load(fullfile('~','local','ec','data','phzfiles',[suffix, '.phz']));
savedir = fullfile('~','projects','archive','2014','ec','stats');

scl   = PHZ;
scl   = phz_blsub(scl, 'baseline');
scl   = phz_reject(scl, 0.05);
behav = PHZ;
behav = phz_subset(behav, PHZ.resp.q1_rt < 7);

region = [1 5];
phz_writetable(scl,...
    'region',   region,...
    'feature',  'mean',...
    'save',     fullfile(savedir, ['mean_',...
                                   phzUtil_num2strRegion(region, '-'),...
                                   suffix, '.csv']));

phz_writetable(behav,...
    'feature',  'rt',...
    'save',     fullfile(savedir, ['rt', suffix, '.csv']));

phz_writetable(behav,...
    'feature',  'acc',...
    'save',     fullfile(savedir, ['acc', suffix, '.csv']));
